### ISSUE TITLE
Most of clip files in validated.tsv lack accent labels

### ISSUE THREAD

**Issue by YQ-Lin** [common-voice/CorporaCreator#121]
I use the tool to deal with the validated.tsv in cv-corpus-7.0-2021-07-21/en, but I found most of the clip files in the validated.tsv lack accent labels. I wonder is it normal? If not, how could I obtain the accent labels?

**Comment by mozgzh** [comment]
The accent metadata is optionally provided by the user that created the clip. Stated another way, clips will not have accent information if the user did not provide it.
